INSERT INTO student (first_name, last_name, age, roll_number, id, address) VALUES
('Arjun',     'Sampath',          17, 101, 1, 'No. 45, 2nd Street, Anna Nagar, Chennai'),
('Sanjay',    'Ram',          16, 102, 2, 'Plot 18, Gandhi Nagar, Coimbatore'),
('Karthik',   'Muthu',          17, 103, 3, 'Door No. 12, Bharathi Street, Madurai'),
('Vignesh',   'Kumar',      18, 104, 4, 'Flat 3A, Lotus Apartments, Trichy'),
('Hariharan', 'Siva',          16, 105, 5, 'No. 78, North Car Street, Tirunelveli'),
('Pranav',    'Raj',        17, 106, 6, 'New No. 24, Old No. 12, Velachery, Chennai'),
('Siddharth', 'Vijay',          17, 107, 7, 'House No. 9, Teachers Colony, Salem'),
('Dhanush',   'Kanesh',          18, 108, 8, 'No. 56, 4th Cross, KK Nagar, Chennai'),
('Gowtham',   'Rajesh',          16, 109, 9, 'Plot No. 7, Alagappa Nagar, Karaikudi'),
('Surya',     'Prakash',    17, 110, 10,'Door No. 15, South Street, Erode'),
('Priya',     'Santham',          17, 111, 11, 'Flat 202, Green Park, Chromepet, Chennai'),
('Sneha',     'Ramesh',          16, 112, 12, 'No. 33, Lakshmi Nagar, Hosur'),
('Divya',     'Madhavan',          17, 113, 13, 'House No. 42, Ponmeni, Madurai'),
('Aishwarya', 'Vignesh',          18, 114, 14, 'No. 19, 3rd Main Road, Gandhipuram, Coimbatore'),
('Keerthana', 'Kamalesh',          16, 115, 15, 'Door No. 8, VOC Street, Tiruppur'),
('Swathi',    'Ragu',          17, 116, 16, 'Plot 25, New Vasanth Nagar, Thanjavur'),
('Nithya',    'Saravanan',          17, 117, 17, 'Flat 5B, Rainbow Towers, Tambaram, Chennai'),
('Shruthi',   'Pirakash',          16, 118, 18, 'No. 67, Annanagar West, Chennai'),
('Madhumitha','Murali',          17, 119, 19, 'Door No. 14, West Masi Street, Madurai'),
('Abinaya',   'Rgavan',          17, 120, 20, 'No. 22, Bharathi Colony, Nagercoil');
