-- CREATE
--		- DATABASE
--		- TABLE
-- DROP
--		- DATABASE
--		- TABLE
-- ALTER
-- TRUNCATE

-- SELECT
--		- WHERE
-- UPDATE
--		- WHERE
-- INSERT INTO

-- DEFAULT VALUES

-- IDENTITY COLUMN
-- 		- GENERATED ALWAYS AS IDENTITY
--		- GENERATED BY DEFAULT AS IDENTITY

-- CONSTRAINTS
--		- CHECK
--		- NOT NULL
-- 		- UNIQUE
--		- PRIMARY KEY
--		- FOREIGN KEY
--			- ON DELETE
-- 			- CASCADE
-- 			- RESTRICT
--			- SET NULL
--			- SET DEFAULT

-- Modifying Tables

-- 		- Adding a Column
-- 		- Removing a Column
-- 		- Adding a Constraint
-- 		- Removing a Constraint
-- 		- Changing a Column's Default Value
-- 		- Changing a Column's Data Type
-- 		- Renaming a Column
-- 		- Renaming a Table